config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      member do
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing
      get :payment
      post :pay
    end
  end

  resources :stories do
    resources :comments, only: [:create]
  end

  # /@使用者名稱/文章標題-123
  get '@:username/:story_id', to: 'pages#show', as: 'story_page'
  
  # /@使用者名稱
  get '@:username', to: 'pages#user', as: 'user_page'

  root 'pages#index'
end

app/views/pages/_comment.html.erb
<article class="comment">
    <span class="profile">
        <%= image_tag comment.user.avatar.variant(resize: '50x50') if comment.user.avatar.attached? %> 
        <span class="username"><%= comment.user.username %></span>
    </span>
    <%= simple_format(comment.content) %>          
</article>

app/views/pages/_comment_area.html.erb
<section class="comment-editor">
    <% if user_signed_in? %>
        <%= form_with model: comment, url: story_comments_path(story), local: false, class: 'comment_form' do |form| %>        
            <%= form.text_area :content, rows: 5, class: "textarea is-small" %>
            <%= form.button '投稿する', class: "button is-primary is-fullwidth" %>
        <% end %> 
    <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: 'button is-success' %>
        <%= link_to '新規登録', new_user_registration_path, class: 'button is-info' %>
    <% end %>
</section>

app/views/pages/demo.html.erb

<div data-controller="demo">
    <input type="text" data-target="demo.content">
    <button data-action="demo#pushme">touch me!!</button>
</div>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css" />
  <title>My Medium</title>
</head>
<body>

  <section class="section">
    <div class="container">
      <section class="columns">
        <!-- left -->
        <section class="column">
          <article>
            <% @clap.first(1).each do |story|  %>
              <figure class="image">
                <%= image_tag story.cover_image.variant(resize: '300x150') %>
              </figure><br>
                <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
                <p class="content has-text-grey"><%= strip_tags(story.content).truncate(200) %></p>
              <footer>
                <p class="has-text-grey-dark"> <%= story.user.username %> </p>
                <p class="has-text-grey-dark"> <%= time_ago_in_words(story.created_at) %> </p>
              </footer>
            <% end %>
          </article>
        </section>
        <!-- left -->
        <!-- middle -->
        <section class="column">
          <% @clap[2, 4].each do |story| %>
            <article class="media">
              <figure class="media-left">
                <%= image_tag story.cover_image.variant(resize: '100x100') %>
              </figure>
              <div class="media-content">
                <h2 class="title is-5"><%= link_to story.title.truncate(20), story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
                <footer>
                  <p class="has-text-grey-dark"> <%= story.user.username %> </p>
                  <p class="has-text-grey-dark"> <%= time_ago_in_words(story.created_at) %> </p>
                </footer>
              </div>
            </article>
          <% end %>
        </section>
        <!-- middle -->
        <!-- right -->
        <section class="column">
          <% @clap[1, 1].each do |story| %>
            <article>
              <figure class="image">
                <%= image_tag story.cover_image.variant(resize: '350x200') %>
              </figure><br>
              <h2 class="title is-5"><%= link_to story.title.truncate(20), story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
              <p class="content has-text-grey"><%= strip_tags(story.content).truncate(200) %></p>
              <footer>
                <p class="has-text-grey-dark"> <%= story.user.username %> </p>
                <p class="has-text-grey-dark"> <%= time_ago_in_words(story.created_at) %> </p>
              </footer>
            </article>
          <% end %>
        </section>
        <!-- right -->
      </section>

      <hr>

      <section class="columns">
        <!-- article list -->
        <section class="column is-two-thirds">
            <h2 class="title is-4 has-text-primary">最新記事一覧</h2>
            <hr>
            <% @stories.first(10).each do |story|  %>
                <article class="media">
                    <div class="media-content">
                    <h2 class="title is-4"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
                    <p class="content has-text-grey"><%= strip_tags(story.content).truncate(200) %></p>
                    <footer>
                        <p class="has-text-grey-dark">
                         <%= story.user.username %> | <%= time_ago_in_words(story.created_at) %>
                        </p>
                    </footer>
                    </div>
                      <% if story.cover_image.attached? %>
                      <figure class="media-right">
                      <%= image_tag story.cover_image.variant(resize: '150x150') %>
                      </figure>
                    <% end %>
                </article>
            <% end %>
        </section>
        <!-- article list -->
        
        <section class="column">
          <h2 class="title is-4 has-text-primary">ランダム記事一覧</h2>
          <hr>
            <% @stories.sample(@range).each do |story| %>
              <article class="media">   
                <div class="media-left">
                  <i class="fas fa-book has-text-dark"></i>
                </div>
              <div class="media-content">
                <p class="title is-5"><%= link_to story.title, story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></p>
                <footer>
                  <p class="content has-text-grey"><%= strip_tags(story.content).truncate(50) %></p>
                </footer>
              </div>
            </article>
          <% end %>
        </section>
      </section>

app/views/pages/show.html.erb
<section class="columns has-text-centered story-content">
  <section class="column is-offset-3 is-6">
    <h1 class="title"><%= @story.title %></h1>

    <span class="profile" data-controller="user">
      <%= image_tag @story.user.avatar.variant(resize: '50x50'), class: 'avatar' if @story.user.avatar.attached? %>
      <span class="username"><%= @story.user.username %></span>
      <%= link_to "#", class: 'follow-button',
                                 data: { action: 'user#follow', 
                                         user: @story.user.id, 
                                         target: 'user.followButton'} do %>
        <%= (user_signed_in? && current_user.follow?(@story.user)) ? 'Followed' : 'Follow' %>
      <% end %>

      <%= link_to "#", class: 'bookmark_button', data: { action: 'user#bookmark', slug: @story.slug } do %>
        <% if user_signed_in? && current_user.bookmark?(@story) %>
          <i class="fas fa-bookmark" data-user-target="bookmark" ></i>
        <% else %>
          <i class="far fa-bookmark" data-user-target="bookmark" ></i>
        <% end %>
        
      <% end %>
    </span>

    <article class="content">
      <%= image_tag @story.cover_image.variant(resize: '1000x500'), class: 'cover-image' if @story.cover_image.attached? %>

      <%= @story.content.html_safe %>

      <footer data-controller="story">
        <%= link_to "#", class: 'clapButton is-size-4 has-text-primary', data: { action: 'story#addClap', slug: @story.slug } do %>
          <i class="fas fa-thumbs-up"></i>
          <span class="clapCount", data-story-target="clapCount" ><%= @story.clap %></span>
        <% end %>
      </footer>
    </article>
    <hr>
    <section class="comments">
      <h2>コメント</h2>

      <%= render 'comment_area', story: @story, comment: @comment %>

      <section class="comment-list">
        <%= render partial: 'comment', collection: @comments %>
      </section>
    </section>
  </section>
</section>